// Text keys
const textKeys = {
  "m_Arca_GlowyHearts_Small": "Glowy Hearts (S)",
  "m_Arca_GlowyHearts_Small_l_Arca_GlowyHeart_Small_L1": "Heart 1 L",
  "m_Arca_GlowyHearts_Small_l_Arca_GlowyHeart_Small_L2": "Heart 2 L",
  "m_Arca_GlowyHearts_Small_l_Arca_GlowyHeart_Small_L3": "Heart 3 L",
  "m_Arca_GlowyHearts_Small_l_Arca_GlowyHeart_Small_L4": "Heart 4 L",
  "m_Arca_GlowyHearts_Small_l_Arca_GlowyHeart_Small_L5": "Heart 5 L",
  "m_Arca_GlowyHearts_Small_l_Arca_GlowyHeart_Small_R1": "Heart 1 R",
  "m_Arca_GlowyHearts_Small_l_Arca_GlowyHeart_Small_R2": "Heart 2 R",
  "m_Arca_GlowyHearts_Small_l_Arca_GlowyHeart_Small_R3": "Heart 3 R",
  "m_Arca_GlowyHearts_Small_l_Arca_GlowyHeart_Small_R4": "Heart 4 R",
  "m_Arca_GlowyHearts_Small_l_Arca_GlowyHeart_Small_R5": "Heart 5 R",
  "m_Arca_GlowyHearts_Small_L": "Glowy Hearts (S) L",
  "m_Arca_GlowyHearts_Small_L_l_Arca_GlowyHeart_Small_L1": "Heart 1",
  "m_Arca_GlowyHearts_Small_L_l_Arca_GlowyHeart_Small_L2": "Heart 2",
  "m_Arca_GlowyHearts_Small_L_l_Arca_GlowyHeart_Small_L3": "Heart 3",
  "m_Arca_GlowyHearts_Small_L_l_Arca_GlowyHeart_Small_L4": "Heart 4",
  "m_Arca_GlowyHearts_Small_L_l_Arca_GlowyHeart_Small_L5": "Heart 5",
  "m_Arca_GlowyHearts_Small_R": "Glowy Hearts (S) R",
  "m_Arca_GlowyHearts_Small_R_l_Arca_GlowyHeart_Small_R1": "Heart 1",
  "m_Arca_GlowyHearts_Small_R_l_Arca_GlowyHeart_Small_R2": "Heart 2",
  "m_Arca_GlowyHearts_Small_R_l_Arca_GlowyHeart_Small_R3": "Heart 3",
  "m_Arca_GlowyHearts_Small_R_l_Arca_GlowyHeart_Small_R4": "Heart 4",
  "m_Arca_GlowyHearts_Small_R_l_Arca_GlowyHeart_Small_R5": "Heart 5",
  "m_Arca_GlowyHearts_Medium": "Glowy Hearts (M)",
  "m_Arca_GlowyHearts_Medium_l_Arca_GlowyHeart_Medium_L1": "Heart 1 L",
  "m_Arca_GlowyHearts_Medium_l_Arca_GlowyHeart_Medium_L2": "Heart 2 L",
  "m_Arca_GlowyHearts_Medium_l_Arca_GlowyHeart_Medium_L3": "Heart 3 L",
  "m_Arca_GlowyHearts_Medium_l_Arca_GlowyHeart_Medium_L4": "Heart 4 L",
  "m_Arca_GlowyHearts_Medium_l_Arca_GlowyHeart_Medium_L5": "Heart 5 L",
  "m_Arca_GlowyHearts_Medium_l_Arca_GlowyHeart_Medium_R1": "Heart 1 R",
  "m_Arca_GlowyHearts_Medium_l_Arca_GlowyHeart_Medium_R2": "Heart 2 R",
  "m_Arca_GlowyHearts_Medium_l_Arca_GlowyHeart_Medium_R3": "Heart 3 R",
  "m_Arca_GlowyHearts_Medium_l_Arca_GlowyHeart_Medium_R4": "Heart 4 R",
  "m_Arca_GlowyHearts_Medium_l_Arca_GlowyHeart_Medium_R5": "Heart 5 R",
  "m_Arca_GlowyHearts_Medium_L": "Glowy Hearts (M) L",
  "m_Arca_GlowyHearts_Medium_L_l_Arca_GlowyHeart_Medium_L1": "Heart 1",
  "m_Arca_GlowyHearts_Medium_L_l_Arca_GlowyHeart_Medium_L2": "Heart 2",
  "m_Arca_GlowyHearts_Medium_L_l_Arca_GlowyHeart_Medium_L3": "Heart 3",
  "m_Arca_GlowyHearts_Medium_L_l_Arca_GlowyHeart_Medium_L4": "Heart 4",
  "m_Arca_GlowyHearts_Medium_L_l_Arca_GlowyHeart_Medium_L5": "Heart 5",
  "m_Arca_GlowyHearts_Medium_R": "Glowy Hearts (M) R",
  "m_Arca_GlowyHearts_Medium_R_l_Arca_GlowyHeart_Medium_R1": "Heart 1",
  "m_Arca_GlowyHearts_Medium_R_l_Arca_GlowyHeart_Medium_R2": "Heart 2",
  "m_Arca_GlowyHearts_Medium_R_l_Arca_GlowyHeart_Medium_R3": "Heart 3",
  "m_Arca_GlowyHearts_Medium_R_l_Arca_GlowyHeart_Medium_R4": "Heart 4",
  "m_Arca_GlowyHearts_Medium_R_l_Arca_GlowyHeart_Medium_R5": "Heart 5",
  "m_Arca_GlowyHearts_Large": "Glowy Hearts (L)",
  "m_Arca_GlowyHearts_Large_l_Arca_GlowyHeart_Large_L1": "Heart 1 L",
  "m_Arca_GlowyHearts_Large_l_Arca_GlowyHeart_Large_L2": "Heart 2 L",
  "m_Arca_GlowyHearts_Large_l_Arca_GlowyHeart_Large_L3": "Heart 3 L",
  "m_Arca_GlowyHearts_Large_l_Arca_GlowyHeart_Large_L4": "Heart 4 L",
  "m_Arca_GlowyHearts_Large_l_Arca_GlowyHeart_Large_L5": "Heart 5 L",
  "m_Arca_GlowyHearts_Large_l_Arca_GlowyHeart_Large_R1": "Heart 1 R",
  "m_Arca_GlowyHearts_Large_l_Arca_GlowyHeart_Large_R2": "Heart 2 R",
  "m_Arca_GlowyHearts_Large_l_Arca_GlowyHeart_Large_R3": "Heart 3 R",
  "m_Arca_GlowyHearts_Large_l_Arca_GlowyHeart_Large_R4": "Heart 4 R",
  "m_Arca_GlowyHearts_Large_l_Arca_GlowyHeart_Large_R5": "Heart 5 R",
  "m_Arca_GlowyHearts_Large_L": "Glowy Hearts (L) L",
  "m_Arca_GlowyHearts_Large_L_l_Arca_GlowyHeart_Large_L1": "Heart 1",
  "m_Arca_GlowyHearts_Large_L_l_Arca_GlowyHeart_Large_L2": "Heart 2",
  "m_Arca_GlowyHearts_Large_L_l_Arca_GlowyHeart_Large_L3": "Heart 3",
  "m_Arca_GlowyHearts_Large_L_l_Arca_GlowyHeart_Large_L4": "Heart 4",
  "m_Arca_GlowyHearts_Large_L_l_Arca_GlowyHeart_Large_L5": "Heart 5",
  "m_Arca_GlowyHearts_Large_R": "Glowy Hearts (L) R",
  "m_Arca_GlowyHearts_Large_R_l_Arca_GlowyHeart_Large_R1": "Heart 1",
  "m_Arca_GlowyHearts_Large_R_l_Arca_GlowyHeart_Large_R2": "Heart 2",
  "m_Arca_GlowyHearts_Large_R_l_Arca_GlowyHeart_Large_R3": "Heart 3",
  "m_Arca_GlowyHearts_Large_R_l_Arca_GlowyHeart_Large_R4": "Heart 4",
  "m_Arca_GlowyHearts_Large_R_l_Arca_GlowyHeart_Large_R5": "Heart 5",
  "m_Arca_CutesyHearts_Small": "Cutesy Hearts (S)",
  "m_Arca_CutesyHearts_Small_l_Arca_CutesyHeart_Small_L1": "Heart 1 L",
  "m_Arca_CutesyHearts_Small_l_Arca_CutesyHeart_Small_L2": "Heart 2 L",
  "m_Arca_CutesyHearts_Small_l_Arca_CutesyHeart_Small_L3": "Heart 3 L",
  "m_Arca_CutesyHearts_Small_l_Arca_CutesyHeart_Small_L4": "Heart 4 L",
  "m_Arca_CutesyHearts_Small_l_Arca_CutesyHeart_Small_L5": "Heart 5 L",
  "m_Arca_CutesyHearts_Small_l_Arca_CutesyHeart_Small_R1": "Heart 1 R",
  "m_Arca_CutesyHearts_Small_l_Arca_CutesyHeart_Small_R2": "Heart 2 R",
  "m_Arca_CutesyHearts_Small_l_Arca_CutesyHeart_Small_R3": "Heart 3 R",
  "m_Arca_CutesyHearts_Small_l_Arca_CutesyHeart_Small_R4": "Heart 4 R",
  "m_Arca_CutesyHearts_Small_l_Arca_CutesyHeart_Small_R5": "Heart 5 R",
  "m_Arca_CutesyHearts_Small_L": "Cutesy Hearts (S) L",
  "m_Arca_CutesyHearts_Small_L_l_Arca_CutesyHeart_Small_L1": "Heart 1",
  "m_Arca_CutesyHearts_Small_L_l_Arca_CutesyHeart_Small_L2": "Heart 2",
  "m_Arca_CutesyHearts_Small_L_l_Arca_CutesyHeart_Small_L3": "Heart 3",
  "m_Arca_CutesyHearts_Small_L_l_Arca_CutesyHeart_Small_L4": "Heart 4",
  "m_Arca_CutesyHearts_Small_L_l_Arca_CutesyHeart_Small_L5": "Heart 5",
  "m_Arca_CutesyHearts_Small_R": "Cutesy Hearts (S) R",
  "m_Arca_CutesyHearts_Small_R_l_Arca_CutesyHeart_Small_R1": "Heart 1",
  "m_Arca_CutesyHearts_Small_R_l_Arca_CutesyHeart_Small_R2": "Heart 2",
  "m_Arca_CutesyHearts_Small_R_l_Arca_CutesyHeart_Small_R3": "Heart 3",
  "m_Arca_CutesyHearts_Small_R_l_Arca_CutesyHeart_Small_R4": "Heart 4",
  "m_Arca_CutesyHearts_Small_R_l_Arca_CutesyHeart_Small_R5": "Heart 5",
  "m_Arca_CutesyHearts_Medium": "Cutesy Hearts (M)",
  "m_Arca_CutesyHearts_Medium_l_Arca_CutesyHeart_Medium_L1": "Heart 1 L",
  "m_Arca_CutesyHearts_Medium_l_Arca_CutesyHeart_Medium_L2": "Heart 2 L",
  "m_Arca_CutesyHearts_Medium_l_Arca_CutesyHeart_Medium_L3": "Heart 3 L",
  "m_Arca_CutesyHearts_Medium_l_Arca_CutesyHeart_Medium_L4": "Heart 4 L",
  "m_Arca_CutesyHearts_Medium_l_Arca_CutesyHeart_Medium_L5": "Heart 5 L",
  "m_Arca_CutesyHearts_Medium_l_Arca_CutesyHeart_Medium_R1": "Heart 1 R",
  "m_Arca_CutesyHearts_Medium_l_Arca_CutesyHeart_Medium_R2": "Heart 2 R",
  "m_Arca_CutesyHearts_Medium_l_Arca_CutesyHeart_Medium_R3": "Heart 3 R",
  "m_Arca_CutesyHearts_Medium_l_Arca_CutesyHeart_Medium_R4": "Heart 4 R",
  "m_Arca_CutesyHearts_Medium_l_Arca_CutesyHeart_Medium_R5": "Heart 5 R",
  "m_Arca_CutesyHearts_Medium_L": "Cutesy Hearts (M) L",
  "m_Arca_CutesyHearts_Medium_L_l_Arca_CutesyHeart_Medium_L1": "Heart 1",
  "m_Arca_CutesyHearts_Medium_L_l_Arca_CutesyHeart_Medium_L2": "Heart 2",
  "m_Arca_CutesyHearts_Medium_L_l_Arca_CutesyHeart_Medium_L3": "Heart 3",
  "m_Arca_CutesyHearts_Medium_L_l_Arca_CutesyHeart_Medium_L4": "Heart 4",
  "m_Arca_CutesyHearts_Medium_L_l_Arca_CutesyHeart_Medium_L5": "Heart 5",
  "m_Arca_CutesyHearts_Medium_R": "Cutesy Hearts (M) R",
  "m_Arca_CutesyHearts_Medium_R_l_Arca_CutesyHeart_Medium_R1": "Heart 1",
  "m_Arca_CutesyHearts_Medium_R_l_Arca_CutesyHeart_Medium_R2": "Heart 2",
  "m_Arca_CutesyHearts_Medium_R_l_Arca_CutesyHeart_Medium_R3": "Heart 3",
  "m_Arca_CutesyHearts_Medium_R_l_Arca_CutesyHeart_Medium_R4": "Heart 4",
  "m_Arca_CutesyHearts_Medium_R_l_Arca_CutesyHeart_Medium_R5": "Heart 5",
  "m_Arca_CutesyHearts_Large": "Cutesy Hearts (L)",
  "m_Arca_CutesyHearts_Large_l_Arca_CutesyHeart_Large_L1": "Heart 1 L",
  "m_Arca_CutesyHearts_Large_l_Arca_CutesyHeart_Large_L2": "Heart 2 L",
  "m_Arca_CutesyHearts_Large_l_Arca_CutesyHeart_Large_L3": "Heart 3 L",
  "m_Arca_CutesyHearts_Large_l_Arca_CutesyHeart_Large_L4": "Heart 4 L",
  "m_Arca_CutesyHearts_Large_l_Arca_CutesyHeart_Large_L5": "Heart 5 L",
  "m_Arca_CutesyHearts_Large_l_Arca_CutesyHeart_Large_R1": "Heart 1 R",
  "m_Arca_CutesyHearts_Large_l_Arca_CutesyHeart_Large_R2": "Heart 2 R",
  "m_Arca_CutesyHearts_Large_l_Arca_CutesyHeart_Large_R3": "Heart 3 R",
  "m_Arca_CutesyHearts_Large_l_Arca_CutesyHeart_Large_R4": "Heart 4 R",
  "m_Arca_CutesyHearts_Large_l_Arca_CutesyHeart_Large_R5": "Heart 5 R",
  "m_Arca_CutesyHearts_Large_L": "Cutesy Hearts (L) L",
  "m_Arca_CutesyHearts_Large_L_l_Arca_CutesyHeart_Large_L1": "Heart 1",
  "m_Arca_CutesyHearts_Large_L_l_Arca_CutesyHeart_Large_L2": "Heart 2",
  "m_Arca_CutesyHearts_Large_L_l_Arca_CutesyHeart_Large_L3": "Heart 3",
  "m_Arca_CutesyHearts_Large_L_l_Arca_CutesyHeart_Large_L4": "Heart 4",
  "m_Arca_CutesyHearts_Large_L_l_Arca_CutesyHeart_Large_L5": "Heart 5",
  "m_Arca_CutesyHearts_Large_R": "Cutesy Hearts (L) R",
  "m_Arca_CutesyHearts_Large_R_l_Arca_CutesyHeart_Large_R1": "Heart 1",
  "m_Arca_CutesyHearts_Large_R_l_Arca_CutesyHeart_Large_R2": "Heart 2",
  "m_Arca_CutesyHearts_Large_R_l_Arca_CutesyHeart_Large_R3": "Heart 3",
  "m_Arca_CutesyHearts_Large_R_l_Arca_CutesyHeart_Large_R4": "Heart 4",
  "m_Arca_CutesyHearts_Large_R_l_Arca_CutesyHeart_Large_R5": "Heart 5"
}
for (var key in textKeys) {
  addTextKey(key, textKeys[key])
}
// Asset preloading
const files = [
  "Models/Large_Hearts/Arca_CutesyHeart_Large_L1.png",
  "Models/Large_Hearts/Arca_CutesyHeart_Large_L2.png",
  "Models/Large_Hearts/Arca_CutesyHeart_Large_L3.png",
  "Models/Large_Hearts/Arca_CutesyHeart_Large_L4.png",
  "Models/Large_Hearts/Arca_CutesyHeart_Large_L5.png",
  "Models/Large_Hearts/Arca_CutesyHeart_Large_R1.png",
  "Models/Large_Hearts/Arca_CutesyHeart_Large_R2.png",
  "Models/Large_Hearts/Arca_CutesyHeart_Large_R3.png",
  "Models/Large_Hearts/Arca_CutesyHeart_Large_R4.png",
  "Models/Large_Hearts/Arca_CutesyHeart_Large_R5.png",
  "Models/Large_Hearts/Arca_GlowyHeart_Large_L1.png",
  "Models/Large_Hearts/Arca_GlowyHeart_Large_L2.png",
  "Models/Large_Hearts/Arca_GlowyHeart_Large_L3.png",
  "Models/Large_Hearts/Arca_GlowyHeart_Large_L4.png",
  "Models/Large_Hearts/Arca_GlowyHeart_Large_L5.png",
  "Models/Large_Hearts/Arca_GlowyHeart_Large_R1.png",
  "Models/Large_Hearts/Arca_GlowyHeart_Large_R2.png",
  "Models/Large_Hearts/Arca_GlowyHeart_Large_R3.png",
  "Models/Large_Hearts/Arca_GlowyHeart_Large_R4.png",
  "Models/Large_Hearts/Arca_GlowyHeart_Large_R5.png",
  "Models/Medium_Hearts/Arca_CutesyHeart_Medium_L1.png",
  "Models/Medium_Hearts/Arca_CutesyHeart_Medium_L2.png",
  "Models/Medium_Hearts/Arca_CutesyHeart_Medium_L3.png",
  "Models/Medium_Hearts/Arca_CutesyHeart_Medium_L4.png",
  "Models/Medium_Hearts/Arca_CutesyHeart_Medium_L5.png",
  "Models/Medium_Hearts/Arca_CutesyHeart_Medium_R1.png",
  "Models/Medium_Hearts/Arca_CutesyHeart_Medium_R2.png",
  "Models/Medium_Hearts/Arca_CutesyHeart_Medium_R3.png",
  "Models/Medium_Hearts/Arca_CutesyHeart_Medium_R4.png",
  "Models/Medium_Hearts/Arca_CutesyHeart_Medium_R5.png",
  "Models/Medium_Hearts/Arca_GlowyHeart_Medium_L1.png",
  "Models/Medium_Hearts/Arca_GlowyHeart_Medium_L2.png",
  "Models/Medium_Hearts/Arca_GlowyHeart_Medium_L3.png",
  "Models/Medium_Hearts/Arca_GlowyHeart_Medium_L4.png",
  "Models/Medium_Hearts/Arca_GlowyHeart_Medium_L5.png",
  "Models/Medium_Hearts/Arca_GlowyHeart_Medium_R1.png",
  "Models/Medium_Hearts/Arca_GlowyHeart_Medium_R2.png",
  "Models/Medium_Hearts/Arca_GlowyHeart_Medium_R3.png",
  "Models/Medium_Hearts/Arca_GlowyHeart_Medium_R4.png",
  "Models/Medium_Hearts/Arca_GlowyHeart_Medium_R5.png",
  "Models/Small_Hearts/Arca_CutesyHeart_Small_L1.png",
  "Models/Small_Hearts/Arca_CutesyHeart_Small_L2.png",
  "Models/Small_Hearts/Arca_CutesyHeart_Small_L3.png",
  "Models/Small_Hearts/Arca_CutesyHeart_Small_L4.png",
  "Models/Small_Hearts/Arca_CutesyHeart_Small_L5.png",
  "Models/Small_Hearts/Arca_CutesyHeart_Small_R1.png",
  "Models/Small_Hearts/Arca_CutesyHeart_Small_R2.png",
  "Models/Small_Hearts/Arca_CutesyHeart_Small_R3.png",
  "Models/Small_Hearts/Arca_CutesyHeart_Small_R4.png",
  "Models/Small_Hearts/Arca_CutesyHeart_Small_R5.png",
  "Models/Small_Hearts/Arca_GlowyHeart_Small_L1.png",
  "Models/Small_Hearts/Arca_GlowyHeart_Small_L2.png",
  "Models/Small_Hearts/Arca_GlowyHeart_Small_L3.png",
  "Models/Small_Hearts/Arca_GlowyHeart_Small_L4.png",
  "Models/Small_Hearts/Arca_GlowyHeart_Small_L5.png",
  "Models/Small_Hearts/Arca_GlowyHeart_Small_R1.png",
  "Models/Small_Hearts/Arca_GlowyHeart_Small_R2.png",
  "Models/Small_Hearts/Arca_GlowyHeart_Small_R3.png",
  "Models/Small_Hearts/Arca_GlowyHeart_Small_R4.png",
  "Models/Small_Hearts/Arca_GlowyHeart_Small_R5.png"
]
for (var file of files) {
  try {
    PIXI.Texture.fromURL(KDModFiles[file])
  } catch (error) {
    console.error('[Arcanox Cute Effects Addon] Caught error while loading texture: ' + file + ' !', error)
  }
}
